// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fleetspeak/src/client/socketservice/proto/fleetspeak_socketservice/config.proto

/*
Package fleetspeak_socketservice is a generated protocol buffer package.

It is generated from these files:
	fleetspeak/src/client/socketservice/proto/fleetspeak_socketservice/config.proto

It has these top-level messages:
	Config
*/
package fleetspeak_socketservice

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The configuration information expected by socketservice.Factory in
// ClientServiceConfig.config.
type Config struct {
	// The given api_proxy_path may be an arbitrary filesystem path and will be
	// used to pair the daemon service with its non-child client process.
	//
	// On Unix in particular, a Unix socket will be created at this path and used
	// for communication between FS and the client.
	//
	// Side note: FS requires the proxy's parent directory's perms to be 0700.
	// If the parent directory doesn't exist, FS will mkdir -p it with perms set
	// to 0700.
	ApiProxyPath string `protobuf:"bytes,5,opt,name=api_proxy_path,json=apiProxyPath" json:"api_proxy_path,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Config) GetApiProxyPath() string {
	if m != nil {
		return m.ApiProxyPath
	}
	return ""
}

func init() {
	proto.RegisterType((*Config)(nil), "fleetspeak.socketservice.Config")
}

func init() {
	proto.RegisterFile("fleetspeak/src/client/socketservice/proto/fleetspeak_socketservice/config.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 137 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xf2, 0x4f, 0xcb, 0x49, 0x4d,
	0x2d, 0x29, 0x2e, 0x48, 0x4d, 0xcc, 0xd6, 0x2f, 0x2e, 0x4a, 0xd6, 0x4f, 0xce, 0xc9, 0x4c, 0xcd,
	0x2b, 0xd1, 0x2f, 0xce, 0x4f, 0xce, 0x4e, 0x2d, 0x29, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x47, 0xa8, 0x8c, 0x47, 0x95, 0x4e, 0xce, 0xcf, 0x4b, 0xcb,
	0x4c, 0xd7, 0x03, 0xab, 0x12, 0x92, 0x40, 0x28, 0xd3, 0x43, 0x51, 0xa6, 0xa4, 0xc7, 0xc5, 0xe6,
	0x0c, 0x56, 0x29, 0xa4, 0xc2, 0xc5, 0x97, 0x58, 0x90, 0x19, 0x5f, 0x50, 0x94, 0x5f, 0x51, 0x19,
	0x5f, 0x90, 0x58, 0x92, 0x21, 0xc1, 0xaa, 0xc0, 0xa8, 0xc1, 0x19, 0xc4, 0x93, 0x58, 0x90, 0x19,
	0x00, 0x12, 0x0c, 0x48, 0x2c, 0xc9, 0x48, 0x62, 0x03, 0x1b, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xe9, 0x17, 0x06, 0x35, 0xa3, 0x00, 0x00, 0x00,
}
