// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fleetspeak/src/client/proto/fleetspeak_client/api.proto

/*
Package fleetspeak_client is a generated protocol buffer package.

It is generated from these files:
	fleetspeak/src/client/proto/fleetspeak_client/api.proto
	fleetspeak/src/client/proto/fleetspeak_client/client.proto

It has these top-level messages:
	ByteBlob
	APIMessage
	CommunicatorConfig
	ClientState
*/
package fleetspeak_client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ByteBlob struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ByteBlob) Reset()                    { *m = ByteBlob{} }
func (m *ByteBlob) String() string            { return proto.CompactTextString(m) }
func (*ByteBlob) ProtoMessage()               {}
func (*ByteBlob) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ByteBlob) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type APIMessage struct {
	Type string               `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Data *google_protobuf.Any `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *APIMessage) Reset()                    { *m = APIMessage{} }
func (m *APIMessage) String() string            { return proto.CompactTextString(m) }
func (*APIMessage) ProtoMessage()               {}
func (*APIMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *APIMessage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *APIMessage) GetData() *google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*ByteBlob)(nil), "fleetspeak.client.ByteBlob")
	proto.RegisterType((*APIMessage)(nil), "fleetspeak.client.APIMessage")
}

func init() {
	proto.RegisterFile("fleetspeak/src/client/proto/fleetspeak_client/api.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4f, 0xcb, 0x49, 0x4d,
	0x2d, 0x29, 0x2e, 0x48, 0x4d, 0xcc, 0xd6, 0x2f, 0x2e, 0x4a, 0xd6, 0x4f, 0xce, 0xc9, 0x4c, 0xcd,
	0x2b, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x47, 0xc8, 0xc5, 0x43, 0xc5, 0x13, 0x0b, 0x32,
	0xf5, 0xc0, 0x72, 0x42, 0x82, 0x08, 0x49, 0x3d, 0x88, 0xa4, 0x94, 0x64, 0x7a, 0x7e, 0x7e, 0x7a,
	0x4e, 0x2a, 0x44, 0x73, 0x52, 0x69, 0x9a, 0x7e, 0x62, 0x5e, 0x25, 0x44, 0xb5, 0x92, 0x1c, 0x17,
	0x87, 0x53, 0x65, 0x49, 0xaa, 0x53, 0x4e, 0x7e, 0x92, 0x90, 0x10, 0x17, 0x4b, 0x4a, 0x62, 0x49,
	0xa2, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x4f, 0x10, 0x98, 0xad, 0xe4, 0xc5, 0xc5, 0xe5, 0x18, 0xe0,
	0xe9, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x0a, 0x52, 0x51, 0x52, 0x59, 0x90, 0x0a, 0x56, 0xc1,
	0x19, 0x04, 0x66, 0x0b, 0x69, 0x40, 0x75, 0x31, 0x29, 0x30, 0x6a, 0x70, 0x1b, 0x89, 0xe8, 0x41,
	0xec, 0xd2, 0x83, 0xd9, 0xa5, 0xe7, 0x98, 0x57, 0x09, 0x31, 0x2b, 0x89, 0x0d, 0x2c, 0x66, 0x0c,
	0x08, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x69, 0xf9, 0xbf, 0xdb, 0x00, 0x00, 0x00,
}
