mysql_data_source_name:"fleetspeak-user:FS_PASSWORD@tcp(mysql-server:3306)/fleetspeak"
https_config: {
  listen_address: "0.0.0.0:9090"
  certificates:"FRONTEND_CERTIFICATE"
  key:"FRONTEND_KEY"
  frontend_config: {
    cleartext_xfcc_config: {
      client_certificate_header: "x-forwarded-client-cert"
    }
  }
}
admin_config: {
  listen_address: "0.0.0.0:9091"
}
health_check_config: {
  listen_address: "0.0.0.0:8080"
}
notification_use_http_notifier:false
