// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fleetspeak/src/client/channel/proto/fleetspeak_channel/channel.proto

/*
Package fleetspeak_channel is a generated protocol buffer package.

It is generated from these files:
	fleetspeak/src/client/channel/proto/fleetspeak_channel/channel.proto

It has these top-level messages:
	StartupData
*/
package fleetspeak_channel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Optional first message sent through a channel when it is created. It is meant
// to contain info about the process that the other end of the channel might
// find useful.
type StartupData struct {
	// Self-reported PID.
	Pid int64 `protobuf:"varint,1,opt,name=pid" json:"pid,omitempty"`
	// Self-reported service version string.
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *StartupData) Reset()                    { *m = StartupData{} }
func (m *StartupData) String() string            { return proto.CompactTextString(m) }
func (*StartupData) ProtoMessage()               {}
func (*StartupData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StartupData) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *StartupData) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*StartupData)(nil), "fleetspeak.channel.StartupData")
}

func init() {
	proto.RegisterFile("fleetspeak/src/client/channel/proto/fleetspeak_channel/channel.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 134 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x72, 0x49, 0xcb, 0x49, 0x4d,
	0x2d, 0x29, 0x2e, 0x48, 0x4d, 0xcc, 0xd6, 0x2f, 0x2e, 0x4a, 0xd6, 0x4f, 0xce, 0xc9, 0x4c, 0xcd,
	0x2b, 0xd1, 0x4f, 0xce, 0x48, 0xcc, 0xcb, 0x4b, 0xcd, 0xd1, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0xd7,
	0x47, 0xa8, 0x89, 0x87, 0x49, 0x40, 0x69, 0x3d, 0xb0, 0x02, 0x21, 0x21, 0x84, 0x0a, 0x3d, 0xa8,
	0x8c, 0x92, 0x25, 0x17, 0x77, 0x70, 0x49, 0x62, 0x51, 0x49, 0x69, 0x81, 0x4b, 0x62, 0x49, 0xa2,
	0x90, 0x00, 0x17, 0x73, 0x41, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x88, 0x29,
	0x24, 0xc1, 0xc5, 0x5e, 0x96, 0x5a, 0x54, 0x9c, 0x99, 0x9f, 0x27, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1,
	0x19, 0x04, 0xe3, 0x26, 0xb1, 0x81, 0x4d, 0x35, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x93,
	0x76, 0x6f, 0x9d, 0x00, 0x00, 0x00,
}
