# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fleetspeak/src/client/daemonservice/proto/fleetspeak_daemonservice/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fleetspeak/src/client/daemonservice/proto/fleetspeak_daemonservice/config.proto',
  package='fleetspeak.daemonservice',
  syntax='proto3',
  serialized_pb=_b('\nOfleetspeak/src/client/daemonservice/proto/fleetspeak_daemonservice/config.proto\x12\x18\x66leetspeak.daemonservice\x1a\x1egoogle/protobuf/duration.proto\"\x91\x04\n\x06\x43onfig\x12\x0c\n\x04\x61rgv\x18\x01 \x03(\t\x12\x35\n\x12inactivity_timeout\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x12\n\nlazy_start\x18\x03 \x01(\x08\x12#\n\x1b\x64isable_resource_monitoring\x18\x04 \x01(\x08\x12\'\n\x1fresource_monitoring_sample_size\x18\x05 \x01(\x05\x12\x31\n)resource_monitoring_sample_period_seconds\x18\x06 \x01(\x05\x12\x14\n\x0cmemory_limit\x18\x07 \x01(\x03\x12\x1a\n\x12monitor_heartbeats\x18\x08 \x01(\x08\x12\x33\n+heartbeat_unresponsive_grace_period_seconds\x18\t \x01(\x05\x12\x32\n*heartbeat_unresponsive_kill_period_seconds\x18\n \x01(\x05\x12>\n\nstd_params\x18\x0b \x01(\x0b\x32*.fleetspeak.daemonservice.Config.StdParams\x1aR\n\tStdParams\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x13\n\x0b\x66lush_bytes\x18\x02 \x01(\x05\x12\x1a\n\x12\x66lush_time_seconds\x18\x03 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_duration__pb2.DESCRIPTOR,])




_CONFIG_STDPARAMS = _descriptor.Descriptor(
  name='StdParams',
  full_name='fleetspeak.daemonservice.Config.StdParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_name', full_name='fleetspeak.daemonservice.Config.StdParams.service_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flush_bytes', full_name='fleetspeak.daemonservice.Config.StdParams.flush_bytes', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flush_time_seconds', full_name='fleetspeak.daemonservice.Config.StdParams.flush_time_seconds', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=589,
  serialized_end=671,
)

_CONFIG = _descriptor.Descriptor(
  name='Config',
  full_name='fleetspeak.daemonservice.Config',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='argv', full_name='fleetspeak.daemonservice.Config.argv', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inactivity_timeout', full_name='fleetspeak.daemonservice.Config.inactivity_timeout', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lazy_start', full_name='fleetspeak.daemonservice.Config.lazy_start', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='disable_resource_monitoring', full_name='fleetspeak.daemonservice.Config.disable_resource_monitoring', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resource_monitoring_sample_size', full_name='fleetspeak.daemonservice.Config.resource_monitoring_sample_size', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='resource_monitoring_sample_period_seconds', full_name='fleetspeak.daemonservice.Config.resource_monitoring_sample_period_seconds', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='memory_limit', full_name='fleetspeak.daemonservice.Config.memory_limit', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='monitor_heartbeats', full_name='fleetspeak.daemonservice.Config.monitor_heartbeats', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heartbeat_unresponsive_grace_period_seconds', full_name='fleetspeak.daemonservice.Config.heartbeat_unresponsive_grace_period_seconds', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heartbeat_unresponsive_kill_period_seconds', full_name='fleetspeak.daemonservice.Config.heartbeat_unresponsive_kill_period_seconds', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='std_params', full_name='fleetspeak.daemonservice.Config.std_params', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CONFIG_STDPARAMS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=671,
)

_CONFIG_STDPARAMS.containing_type = _CONFIG
_CONFIG.fields_by_name['inactivity_timeout'].message_type = google_dot_protobuf_dot_duration__pb2._DURATION
_CONFIG.fields_by_name['std_params'].message_type = _CONFIG_STDPARAMS
DESCRIPTOR.message_types_by_name['Config'] = _CONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Config = _reflection.GeneratedProtocolMessageType('Config', (_message.Message,), dict(

  StdParams = _reflection.GeneratedProtocolMessageType('StdParams', (_message.Message,), dict(
    DESCRIPTOR = _CONFIG_STDPARAMS,
    __module__ = 'fleetspeak.src.client.daemonservice.proto.fleetspeak_daemonservice.config_pb2'
    # @@protoc_insertion_point(class_scope:fleetspeak.daemonservice.Config.StdParams)
    ))
  ,
  DESCRIPTOR = _CONFIG,
  __module__ = 'fleetspeak.src.client.daemonservice.proto.fleetspeak_daemonservice.config_pb2'
  # @@protoc_insertion_point(class_scope:fleetspeak.daemonservice.Config)
  ))
_sym_db.RegisterMessage(Config)
_sym_db.RegisterMessage(Config.StdParams)


# @@protoc_insertion_point(module_scope)
