# Copyright 2017 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fleetspeak/src/server/proto/fleetspeak_server/resource.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='fleetspeak/src/server/proto/fleetspeak_server/resource.proto',
  package='fleetspeak.server',
  syntax='proto3',
  serialized_pb=_b('\n<fleetspeak/src/server/proto/fleetspeak_server/resource.proto\x12\x11\x66leetspeak.server\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x03\n\x19\x43lientResourceUsageRecord\x12\r\n\x05scope\x18\x01 \x01(\t\x12\x0b\n\x03pid\x18\x02 \x01(\x03\x12\x36\n\x12process_start_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10\x63lient_timestamp\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x34\n\x10server_timestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1a\n\x12mean_user_cpu_rate\x18\x06 \x01(\x02\x12\x19\n\x11max_user_cpu_rate\x18\x07 \x01(\x02\x12\x1c\n\x14mean_system_cpu_rate\x18\x08 \x01(\x02\x12\x1b\n\x13max_system_cpu_rate\x18\t \x01(\x02\x12 \n\x18mean_resident_memory_mib\x18\n \x01(\x05\x12\x1f\n\x17max_resident_memory_mib\x18\x0b \x01(\x05\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_CLIENTRESOURCEUSAGERECORD = _descriptor.Descriptor(
  name='ClientResourceUsageRecord',
  full_name='fleetspeak.server.ClientResourceUsageRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scope', full_name='fleetspeak.server.ClientResourceUsageRecord.scope', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pid', full_name='fleetspeak.server.ClientResourceUsageRecord.pid', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='process_start_time', full_name='fleetspeak.server.ClientResourceUsageRecord.process_start_time', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='client_timestamp', full_name='fleetspeak.server.ClientResourceUsageRecord.client_timestamp', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='server_timestamp', full_name='fleetspeak.server.ClientResourceUsageRecord.server_timestamp', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_user_cpu_rate', full_name='fleetspeak.server.ClientResourceUsageRecord.mean_user_cpu_rate', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_user_cpu_rate', full_name='fleetspeak.server.ClientResourceUsageRecord.max_user_cpu_rate', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_system_cpu_rate', full_name='fleetspeak.server.ClientResourceUsageRecord.mean_system_cpu_rate', index=7,
      number=8, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_system_cpu_rate', full_name='fleetspeak.server.ClientResourceUsageRecord.max_system_cpu_rate', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mean_resident_memory_mib', full_name='fleetspeak.server.ClientResourceUsageRecord.mean_resident_memory_mib', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_resident_memory_mib', full_name='fleetspeak.server.ClientResourceUsageRecord.max_resident_memory_mib', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=517,
)

_CLIENTRESOURCEUSAGERECORD.fields_by_name['process_start_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CLIENTRESOURCEUSAGERECORD.fields_by_name['client_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_CLIENTRESOURCEUSAGERECORD.fields_by_name['server_timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ClientResourceUsageRecord'] = _CLIENTRESOURCEUSAGERECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClientResourceUsageRecord = _reflection.GeneratedProtocolMessageType('ClientResourceUsageRecord', (_message.Message,), dict(
  DESCRIPTOR = _CLIENTRESOURCEUSAGERECORD,
  __module__ = 'fleetspeak.src.server.proto.fleetspeak_server.resource_pb2'
  # @@protoc_insertion_point(class_scope:fleetspeak.server.ClientResourceUsageRecord)
  ))
_sym_db.RegisterMessage(ClientResourceUsageRecord)


# @@protoc_insertion_point(module_scope)
