name: GitHub Actions Demo
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      MYSQL_TEST_USER: root
      MYSQL_TEST_PASSWORD: root
      MYSQL_TEST_ADDR: 127.0.0.1:3306
      MYSQL_TEST_E2E_DB: e2e_test_db
    steps:
      - uses: actions/checkout@v2
      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_TEST_E2E_DB }};' -u${{ env.MYSQL_TEST_USER }} -p${{ env.MYSQL_TEST_PASSWORD }}
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15'
      - name: Set up Go
        run: |
          go get -u golang.org/x/lint/golint
          go get -u -v github.com/golang/protobuf/protoc-gen-go@v1.4.2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Set up Python
        run: |
          pip install -e ./fleetspeak_python
          pip install -e ./frr_python
